# Generated by Django 5.2.6 on 2025-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('uri', models.URLField()),
                ('subscribers_count', models.IntegerField(blank=True, null=True)),
                ('subscribers_count_updated', models.DateTimeField(blank=True, null=True)),
                ('posts_two_weeks_count', models.IntegerField(blank=True, null=True)),
                ('posts_two_weeks_count_updated', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subreddits',
                'ordering': ['-date_created'],
            },
        ),
    ]
