# Generated by Django 5.2.6 on 2025-10-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='subreddit_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
