# Generated by Django 5.2.6 on 2025-10-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_subreddit_subreddit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreddit',
            name='posts_two_weeks_count',
        ),
        migrations.RemoveField(
            model_name='subreddit',
            name='posts_two_weeks_count_updated',
        ),
        migrations.RemoveField(
            model_name='subreddit',
            name='subscribers_count',
        ),
        migrations.RemoveField(
            model_name='subreddit',
            name='subscribers_count_updated',
        ),
        migrations.CreateModel(
            name='SubredditDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribers_count', models.IntegerField(blank=True, null=True)),
                ('posts_two_weeks_count', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.subreddit')),
            ],
            options={
                'db_table': 'subreddits_daily_stats',
                'ordering': ['-date_created'],
            },
        ),
    ]
