# Generated by Django 5.2.6 on 2025-10-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_subreddit_posts_two_weeks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subredditdailystats',
            name='avg_post_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subredditdailystats',
            name='avg_upvote_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subredditdailystats',
            name='engagement_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subredditdailystats',
            name='total_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
