# Generated by Django 5.2.6 on 2025-10-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_subredditdailystats_avg_post_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subredditdailystats',
            old_name='posts_two_weeks_count',
            new_name='posts_count',
        ),
    ]
