# Generated by Django 5.2.6 on 2025-10-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_posts_two_week_count_to_posts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
