# Generated by Django 5.2.6 on 2025-10-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_subreddit_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='land_area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
