# Generated by Django 5.2.6 on 2025-10-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_subreddit_land_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='residents_over_18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
