# Generated by Django 5.2.6 on 2025-10-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_subreddit_region_subreddit_residents_over_18_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created_utc', models.DateTimeField()),
                ('created_local', models.DateTimeField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('upvote_ratio', models.FloatField(blank=True, null=True)),
                ('num_comments', models.IntegerField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('engagement_collected', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.subreddit')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_utc'],
                'indexes': [models.Index(fields=['subreddit', 'created_local'], name='posts_subredd_76e3bc_idx'), models.Index(fields=['engagement_collected', 'created_utc'], name='posts_engagem_1ca2cf_idx')],
            },
        ),
    ]
