# Generated by Django 5.2.6 on 2025-10-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='distinguished',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_self',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='link_flair_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='over_18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='permalink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='stickied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
