# Generated by Django 5.2.6 on 2025-10-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_post_distinguished_post_is_self_post_link_flair_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estimated_downvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='estimated_upvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
