# Generated by Django 5.2.6 on 2025-10-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_post_estimated_downvotes_post_estimated_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subredditdailystats',
            name='total_estimated_downvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subredditdailystats',
            name='total_estimated_upvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
