# Generated by Django 5.2.6 on 2025-10-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_subredditdailystats_total_estimated_downvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='pop_density_density',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
