# Generated by Django 5.2.6 on 2025-10-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_subreddit_pop_density_density'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subreddit',
            old_name='pop_density_density',
            new_name='pop_density',
        ),
    ]
