# Generated by Django 5.2.6 on 2025-11-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_rename_pop_density_density_subreddit_pop_density'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('topic', 'Topic'), ('content_type', 'Content Type'), ('sentiment', 'Sentiment'), ('geographic', 'Geographic'), ('temporal', 'Temporal'), ('meta', 'Meta')], db_index=True, max_length=20)),
                ('description', models.TextField(help_text='When to apply this tag - used for AI context')),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary tags shown more prominently')),
                ('display_order', models.IntegerField(default=999)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(choices=[('ai', 'AI'), ('admin', 'Admin'), ('system', 'System')], default='system', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['category', 'display_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='tags_categor_85002e_idx'), models.Index(fields=['usage_count'], name='tags_usage_c_26dec2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AITaggingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('prompt_template', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(default='v1.0', max_length=20)),
                ('raw_response', models.JSONField()),
                ('tags_applied', models.JSONField()),
                ('confidence_scores', models.JSONField(null=True)),
                ('processing_time_ms', models.IntegerField(null=True)),
                ('token_count', models.IntegerField(null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.post')),
            ],
            options={
                'db_table': 'ai_tagging_logs',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['-date_created'], name='ai_tagging__date_cr_2dff39_idx'), models.Index(fields=['post', '-date_created'], name='ai_tagging__post_id_a47733_idx'), models.Index(fields=['success'], name='ai_tagging__success_49fb3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_by', models.CharField(max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tracker.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_posts', to='tracker.tag')),
            ],
            options={
                'db_table': 'post_tags',
                'indexes': [models.Index(fields=['post', 'tag'], name='post_tags_post_id_3acd6a_idx'), models.Index(fields=['needs_review', 'reviewed'], name='post_tags_needs_r_d53c4c_idx'), models.Index(fields=['applied_at'], name='post_tags_applied_6e152d_idx')],
                'unique_together': {('post', 'tag')},
            },
        ),
    ]
