# Generated by Django 5.2.6 on 2025-11-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_tag_aitagginglog_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags_collected',
            field=models.BooleanField(default=False),
        ),
    ]
