# Generated by Django 5.2.6 on 2025-11-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_post_tags_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_local',
            field=models.DateField(),
        ),
    ]
