# Generated by Django 5.2.6 on 2025-12-04 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_alter_post_created_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('subscribers_7day_avg', models.FloatField(blank=True, null=True)),
                ('posts_7day_avg', models.FloatField(blank=True, null=True)),
                ('score_7day_avg', models.FloatField(blank=True, null=True)),
                ('comments_7day_avg', models.FloatField(blank=True, null=True)),
                ('upvotes_7day_avg', models.FloatField(blank=True, null=True)),
                ('subscribers_30day_avg', models.FloatField(blank=True, null=True)),
                ('posts_30day_avg', models.FloatField(blank=True, null=True)),
                ('score_30day_avg', models.FloatField(blank=True, null=True)),
                ('comments_30day_avg', models.FloatField(blank=True, null=True)),
                ('upvotes_30day_avg', models.FloatField(blank=True, null=True)),
                ('subscribers_wow_change', models.FloatField(blank=True, null=True)),
                ('posts_wow_change', models.FloatField(blank=True, null=True)),
                ('score_wow_change', models.FloatField(blank=True, null=True)),
                ('comments_wow_change', models.FloatField(blank=True, null=True)),
                ('upvotes_wow_change', models.FloatField(blank=True, null=True)),
                ('subreddits_included', models.IntegerField(default=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'global_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MetricsDispersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('entity_type', models.CharField(choices=[('global', 'Global'), ('subreddit', 'Subreddit')], db_index=True, max_length=20)),
                ('metric_name', models.CharField(db_index=True, max_length=50)),
                ('median', models.FloatField(blank=True, null=True)),
                ('std_dev', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('p25', models.FloatField(blank=True, null=True)),
                ('p75', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('subreddit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.subreddit')),
            ],
            options={
                'db_table': 'metrics_dispersion',
                'ordering': ['-date', 'entity_type', 'metric_name'],
                'indexes': [models.Index(fields=['date', 'entity_type'], name='metrics_dis_date_9fa91a_idx'), models.Index(fields=['date', 'entity_type', 'metric_name'], name='metrics_dis_date_969f0b_idx'), models.Index(fields=['subreddit', 'date'], name='metrics_dis_subredd_37bac5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubredditMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('subscribers_7day_avg', models.FloatField(blank=True, null=True)),
                ('posts_7day_avg', models.FloatField(blank=True, null=True)),
                ('score_7day_avg', models.FloatField(blank=True, null=True)),
                ('comments_7day_avg', models.FloatField(blank=True, null=True)),
                ('upvotes_7day_avg', models.FloatField(blank=True, null=True)),
                ('subscribers_30day_avg', models.FloatField(blank=True, null=True)),
                ('posts_30day_avg', models.FloatField(blank=True, null=True)),
                ('score_30day_avg', models.FloatField(blank=True, null=True)),
                ('comments_30day_avg', models.FloatField(blank=True, null=True)),
                ('upvotes_30day_avg', models.FloatField(blank=True, null=True)),
                ('subscribers_wow_change', models.FloatField(blank=True, null=True)),
                ('posts_wow_change', models.FloatField(blank=True, null=True)),
                ('score_wow_change', models.FloatField(blank=True, null=True)),
                ('comments_wow_change', models.FloatField(blank=True, null=True)),
                ('upvotes_wow_change', models.FloatField(blank=True, null=True)),
                ('subscribers_7day_rank', models.IntegerField(blank=True, null=True)),
                ('posts_7day_rank', models.IntegerField(blank=True, null=True)),
                ('score_7day_rank', models.IntegerField(blank=True, null=True)),
                ('comments_7day_rank', models.IntegerField(blank=True, null=True)),
                ('upvotes_7day_rank', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.subreddit')),
            ],
            options={
                'db_table': 'subreddit_metrics',
                'ordering': ['-date', 'subreddit__name'],
                'indexes': [models.Index(fields=['subreddit', 'date'], name='subreddit_m_subredd_65483e_idx'), models.Index(fields=['date'], name='subreddit_m_date_7dfb9d_idx')],
                'unique_together': {('subreddit', 'date')},
            },
        ),
    ]
